[package]
name = "appl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "4.3.23", features = ["derive"]}
colored = "2.0.4"
dialoguer = "0.10.4"
indicatif = "0.17.6"
serde = { version = "1.0.185", features = ["derive"] }
serde_json = "1.0.105"
whoami = "1.4.1"
