# appl example toml script

# Package name. All-lowercase names are preferred.
name = "vim"
# The version of a package. Use a SemVer. 
version = "9.0.0"
# Development branch. Options are:
# dev, prod, git, beta, nightly
branch = "prod"
# What architecture is this package for? Options are:
# X64, X32, arm64, any
arch = "X64"
# Array of dependencies to use. Because appl is centered around portability, this should seldom be used.
dependencies = []
# Download size of package, in MB.
download_size = 7
# Total install size, **without** dependencies
install_size = 9
# URL to source code from/download.
url="https://github.com/vim/vim/archive/refs/tags/v9.0.2048.zip"
# Build function 
build = [
    "print hi"
]
